import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { AlertTriangle, ArrowRight, LockKeyhole, ShieldCheck } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'

const loginSchema=z.object({email:z.email('Enter a valid email address'),password:z.string().min(6,'Password must contain at least 6 characters')})
const registerSchema=loginSchema.extend({name:z.string().min(2,'Enter your name').max(80)})
type AuthForm={name?:string;email:string;password:string}
export function AuthPage({mode}:{mode:'login'|'register'}){
 const {user,login,register,configured}=useAuth();const nav=useNavigate();const location=useLocation();const [serverError,setServerError]=useState('');const isRegister=mode==='register'
 const {register:field,handleSubmit,formState:{errors,isSubmitting}}=useForm<AuthForm>({resolver:zodResolver(isRegister?registerSchema:loginSchema)})
 if(user)return <Navigate to="/dashboard" replace/>
 const submit=async(data:AuthForm)=>{setServerError('');if(!configured){setServerError('Firebase is not configured yet. Add project credentials to .env.');return}try{if(isRegister)await register(data.name!,data.email,data.password);else await login(data.email,data.password);nav((location.state as {from?:string})?.from||'/dashboard')}catch{setServerError(isRegister?'Registration failed. Check the details or try another email.':'Login failed. Check your email and password.') }}
 return <section className="page"><div className="container-x form-panel" style={{maxWidth:520}}><div className="icon-box"><ShieldCheck/></div><span className="eyebrow">Secure access</span><h1 style={{fontSize:40,letterSpacing:'-.05em',margin:'16px 0 10px'}}>{isRegister?'Create your account':'Welcome back'}</h1><p className="muted" style={{lineHeight:1.6,margin:'0 0 28px'}}>{isRegister?'Register to submit and privately track complaints.':'Sign in to access your protected complaint dashboard.'}</p>{!configured&&<div className="alert" style={{marginBottom:20}}><AlertTriangle size={19}/>Firebase connection is awaiting project configuration.</div>}{serverError&&<div className="alert" style={{marginBottom:20}}><AlertTriangle size={19}/>{serverError}</div>}<form onSubmit={handleSubmit(submit)} style={{display:'grid',gap:18}}>{isRegister&&<div className="field"><label htmlFor="name">Full name</label><input id="name" className="input" autoComplete="name" {...field('name')}/>{errors.name&&<span className="field-error">{errors.name.message}</span>}</div>}<div className="field"><label htmlFor="email">Email address</label><input id="email" className="input" type="email" autoComplete="email" {...field('email')}/>{errors.email&&<span className="field-error">{errors.email.message}</span>}</div><div className="field"><label htmlFor="password">Password</label><input id="password" className="input" type="password" autoComplete={isRegister?'new-password':'current-password'} {...field('password')}/>{errors.password&&<span className="field-error">{errors.password.message}</span>}</div><button className="btn btn-primary" disabled={isSubmitting}>{isSubmitting?'Securing access…':isRegister?'Register securely':'Login'}<ArrowRight size={17}/></button></form><div style={{display:'flex',gap:10,alignItems:'center',marginTop:22,color:'#76868d',fontSize:13}}><LockKeyhole size={15}/>{isRegister?'Already registered?':'New to EduJustice?'} <Link className="red" to={isRegister?'/login':'/register'}>{isRegister?'Login':'Create account'}</Link></div></div></section>
}
