import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileWarning, Plus } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader'
import { useAuth } from '../contexts/AuthContext'
import { getUserComplaints } from '../services/complaints'
import type { Complaint } from '../types'

function date(value:Complaint['createdAt']){if(!value)return 'Pending';return (value instanceof Date?value:value.toDate()).toLocaleDateString()}
export function DashboardPage(){const {user,configured}=useAuth();const [items,setItems]=useState<Complaint[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{if(!user||!configured){setLoading(false);return}getUserComplaints(user.uid).then(setItems).catch(()=>setError('Complaints could not be loaded. Check your connection and try again.')).finally(()=>setLoading(false))},[user,configured]);const stats=useMemo(()=>({total:items.length,active:items.filter(x=>x.status!=='Resolved').length,resolved:items.filter(x=>x.status==='Resolved').length}),[items]);const statCards=[{Icon:FileWarning,label:'Total complaints',value:stats.total},{Icon:Clock3,label:'Active cases',value:stats.active},{Icon:CheckCircle2,label:'Resolved',value:stats.resolved}]
 return <><PageHeader eyebrow="Private command centre" title={`Welcome, ${user?.displayName?.split(' ')[0]||user?.email?.split('@')[0]||'student'}.`} description="Monitor every complaint you submitted from one secure, account-protected dashboard."/><section className="page"><div className="container-x"><div className="grid-3" style={{marginBottom:24}}>{statCards.map(({Icon,label,value})=><article className="card" key={label}><Icon size={24} color="var(--red)"/><div style={{fontSize:42,fontWeight:850,letterSpacing:'-.05em',margin:'18px 0 5px'}}>{String(value).padStart(2,'0')}</div><span className="section-index">{label}</span></article>)}</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,margin:'42px 0 18px'}}><h2 style={{margin:0}}>Recent complaints</h2><Link className="btn btn-primary" to="/report"><Plus size={16}/>New report</Link></div>{error&&<div className="alert" style={{marginBottom:18}}><AlertTriangle size={18}/>{error}</div>}{loading?<div className="card muted">Loading protected records…</div>:items.length===0?<div className="card" style={{textAlign:'center',padding:60}}><FileWarning size={36} color="var(--red)" style={{margin:'0 auto 18px'}}/><h3>No complaints yet.</h3><p>Your submitted complaints will appear here.</p><Link className="btn btn-secondary" style={{marginTop:24}} to="/report">Start a report <ArrowRight size={16}/></Link></div>:<div className="table-shell"><table className="data-table"><thead><tr><th>ID</th><th>Category</th><th>Institution</th><th>Date</th><th>Status</th><th>View</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td className="mono">{x.complaintId}</td><td>{x.issueType}</td><td>{x.institution}</td><td>{date(x.createdAt)}</td><td><span className="status-pill">{x.status}</span></td><td><Link className="red" to={`/track?code=${encodeURIComponent(x.complaintId)}`}>Track</Link></td></tr>)}</tbody></table></div>}</div></section></>}
