import { useEffect, useState } from 'react'
import { BarChart3, Building2, CheckCircle2, Clock3, FileWarning } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { doc, getDoc } from 'firebase/firestore'
import { PageHeader } from '../components/ui/PageHeader'
import { db, isFirebaseConfigured } from '../firebase/config'

interface PlatformStats{total:number;resolved:number;institutions:number;underReview:number;categories:{name:string;value:number}[];monthly:{month:string;complaints:number}[];statuses:{name:string;value:number}[]}
export function StatisticsPage(){const [stats,setStats]=useState<PlatformStats|null>(null);const [loading,setLoading]=useState(true);const [unavailable,setUnavailable]=useState(false);useEffect(()=>{if(!isFirebaseConfigured){setLoading(false);return}getDoc(doc(db,'statistics','platform')).then(s=>{if(s.exists())setStats(s.data() as PlatformStats)}).catch(()=>setUnavailable(true)).finally(()=>setLoading(false))},[]);const cards=[[FileWarning,'Complaints received',stats?.total||0],[CheckCircle2,'Complaints resolved',stats?.resolved||0],[Building2,'Institutions monitored',stats?.institutions||0],[Clock3,'Cases under review',stats?.underReview||0]] as const
 return <><PageHeader eyebrow="Verified platform data" title="Transparency in numbers." description="Only verified records from the EduJustice platform are counted. We do not present invented real-world statistics."/><section className="page"><div className="container-x"><div className="grid-4">{cards.map(([Icon,label,value])=><article className="card" key={label}><Icon color="var(--red)"/><div style={{fontSize:46,fontWeight:850,margin:'18px 0 4px',letterSpacing:'-.06em'}}>{value.toLocaleString()}</div><span className="section-index">{label}</span></article>)}</div>{loading?<div className="card muted" style={{marginTop:24}}>Loading verified statistics…</div>:unavailable?<div className="alert" style={{marginTop:24}}>Verified statistics are temporarily unavailable. Please try again later.</div>:!stats?<div className="card" style={{marginTop:24,textAlign:'center',padding:60}}><BarChart3 color="var(--red)" size={38} style={{margin:'0 auto 16px'}}/><h3>Verified data is being collected.</h3><p>Data will appear as verified platform records are collected.</p></div>:<div className="grid-2" style={{marginTop:24}}><Chart title="Complaint categories"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={stats.categories} dataKey="value" nameKey="name" innerRadius={58} outerRadius={95}>{stats.categories.map((_,i)=><Cell key={i} fill={['#ff3c31','#31d5ff','#b8ff38','#ff9f31','#8b5cff'][i%5]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Chart><Chart title="Monthly complaints"><ResponsiveContainer width="100%" height={280}><LineChart data={stats.monthly}><CartesianGrid stroke="rgba(255,255,255,.06)"/><XAxis dataKey="month" stroke="#62727a"/><YAxis stroke="#62727a"/><Tooltip/><Line dataKey="complaints" stroke="#ff3c31" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart><Chart title="Resolution status"><ResponsiveContainer width="100%" height={280}><BarChart data={stats.statuses}><CartesianGrid stroke="rgba(255,255,255,.06)"/><XAxis dataKey="name" stroke="#62727a"/><YAxis stroke="#62727a"/><Tooltip/><Bar dataKey="value" fill="#ff3c31"/></BarChart></ResponsiveContainer></Chart></div>}</div></section></>}
function Chart({title,children}:{title:string;children:React.ReactNode}){return <article className="card"><h3>{title}</h3>{children}</article>}
