import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { AlertTriangle, Check, LockKeyhole, Search } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader'
import { useAuth } from '../contexts/AuthContext'
import { trackComplaint } from '../services/complaints'
import type { Complaint, ComplaintStatus } from '../types'

const statuses:ComplaintStatus[]=['Submitted','Under Review','Investigation','Action Taken','Resolved']
function date(value:Complaint['createdAt']){if(!value)return 'Pending';if(value instanceof Date)return value.toLocaleDateString();return value.toDate().toLocaleDateString()}
export function TrackPage(){const {user,configured}=useAuth();const [searchParams,setSearchParams]=useSearchParams();const [code,setCode]=useState((searchParams.get('code')||'').toUpperCase());const [record,setRecord]=useState<Complaint|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const search=async(e:React.FormEvent)=>{e.preventDefault();setError('');setRecord(null);if(!user){setError('Sign in to verify complaint ownership before tracking.');return}if(!configured){setError('Firebase is not configured yet.');return}if(!/^EDU-\d{4}-[A-Z0-9]{5}$/.test(code.toUpperCase())){setError('Enter a valid ID such as EDU-2026-8F42K.');return}setLoading(true);try{const result=await trackComplaint(code,user.uid);if(!result)setError('No complaint matching this ID belongs to your account.');else{setRecord(result);setSearchParams({code:result.complaintId},{replace:true})}}catch{setError('Tracking is temporarily unavailable. Try again.')}finally{setLoading(false)}}
 return <><PageHeader eyebrow="Private case tracking" title="Track your complaint." description="Complaint details are visible only after authentication and ownership verification."/><section className="page"><div className="container-x" style={{maxWidth:880}}><form className="form-panel" onSubmit={search} style={{display:'grid',gap:16}}><div className="field"><label htmlFor="complaintId">Enter complaint ID</label><input id="complaintId" className="input mono" placeholder="EDU-2026-8F42K" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div>{!user&&<div className="alert"><LockKeyhole size={19}/><span><Link to="/login" state={{from:`/track${code?`?code=${encodeURIComponent(code)}`:''}`}} className="red">Sign in</Link> to verify ownership.</span></div>}{error&&<div className="alert"><AlertTriangle size={19}/>{error}</div>}<button className="btn btn-primary" disabled={loading}>{loading?'Verifying…':'Verify and track'}<Search size={17}/></button></form>{record&&<div className="card" style={{marginTop:24,padding:'clamp(22px,4vw,40px)'}}><div style={{display:'flex',justifyContent:'space-between',gap:18,flexWrap:'wrap'}}><div><span className="section-index">COMPLAINT ID</span><h2 className="mono" style={{color:'var(--acid)'}}>{record.complaintId}</h2></div><span className="status-pill">{record.status}</span></div><div className="grid-3" style={{margin:'28px 0'}}>{[['Category',record.issueType],['Institution',record.institution],['Submitted',date(record.createdAt)],['Last updated',date(record.updatedAt)]].map(([a,b])=><div key={a}><span className="section-index">{a}</span><div style={{marginTop:8}}>{b}</div></div>)}</div><div style={{display:'grid',gridTemplateColumns:`repeat(${statuses.length},1fr)`,gap:4,marginTop:34}}>{statuses.map((status,i)=>{const active=i<=statuses.indexOf(record.status);return <div key={status} style={{minWidth:0}}><div style={{height:4,background:active?'var(--red)':'#253038',boxShadow:active?'0 0 10px rgba(255,60,49,.4)':'none'}}/><div style={{display:'flex',gap:7,alignItems:'center',marginTop:10,color:active?'#d7e0e4':'#57676f',fontSize:10,textTransform:'uppercase'}}>{active&&<Check size={12}/>}<span>{status}</span></div></div>})}</div>{record.resolutionNotes&&<div className="alert success" style={{marginTop:28}}><Check size={18}/><span><b>Resolution notes:</b> {record.resolutionNotes}</span></div>}</div>}</div></section></>}
